# Generated by Django 2.1.3 on 2019-01-16 08:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ATOM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 16, 8, 4, 37, 946957, tzinfo=utc)),
        ),
    ]
