# Generated by Django 2.1.3 on 2019-01-16 08:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ATOM', '0002_auto_20190116_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 16, 8, 5, 11, 874518, tzinfo=utc)),
        ),
    ]
