# Generated by Django 2.1.3 on 2019-01-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATOM', '0004_auto_20190116_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='m_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
