# Generated by Django 2.1.3 on 2019-01-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATOM', '0005_post_m_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='m_file',
        ),
    ]
