# Generated by Django 2.1.3 on 2019-01-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATOM', '0006_remove_post_m_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
                ('imgName', models.CharField(max_length=40)),
            ],
        ),
    ]
