# Generated by Django 2.1.3 on 2019-01-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATOM', '0008_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='userGender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userHeadIconPath',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
