# Generated by Django 2.1.3 on 2019-02-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATOM', '0010_userinfo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='eyeCountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogID', models.CharField(max_length=10)),
                ('eyeCount', models.BigIntegerField()),
                ('heartCount', models.BigIntegerField()),
                ('starCount', models.BigIntegerField()),
            ],
        ),
    ]
