# Generated by Django 2.1.3 on 2019-02-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATOM', '0011_eyecountmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='userStarID',
            field=models.TextField(blank=True, null=True),
        ),
    ]
