# Generated by Django 2.1.3 on 2019-06-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATOM', '0012_userinfo_userstarid'),
    ]

    operations = [
        migrations.CreateModel(
            name='toolUseCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toolID', models.CharField(max_length=10)),
                ('toolCount', models.BigIntegerField()),
            ],
        ),
    ]
